export const PROP_FIRMS = [
  '5%ers',
  'Alpha Capital Group',
  'Apex Trader Funding',
  'Audacity Capital',
  'Blue Guardian',
  'BluFX',
  'Breakout Funding',
  'BrightFunded',
  'City Traders Imperium',
  'Crypto Fund Trader',
  'E8 Funding',
  'Earn2Trade',
  'Elite Trader Funding',
  'Fidelcrest',
  'Finotive Funding',
  'Forex Capital Funds',
  'FTMO',
  'Funded Trading Plus',
  'FundedNext',
  'Funding Frontier',
  'Funding Pips',
  'Funding Talent',
  'Funding Traders Market',
  'FX2Funding',
  'FXIFY',
  'Goat Funded Trader',
  'Hantec Traders',
  'ifunds',
  'Instant Funding',
  'Lark Funding',
  'Leeloo Trading',
  'Lux Trading Firm',
  'Maven Trading',
  'Ment Funding',
  'MyForexFunds',
  'Nordic Funder',
  'OneUp Trader',
  'OspreyFX Funding',
  'Pipfarm',
  'QuantTekel',
  'Rocket21 Challenge',
  'SabioTrade',
  'ScaleUp Capital',
  'Skilled Funded Traders',
  'Smart Prop Trader',
  'Super Funded',
  'SurgeTrader',
  'The Funded Trader',
  'The Trading Pit',
  'The5ers',
  'Topstep',
  'TradeDay',
  'Traders With Edge',
  'TradersEdgeFX',
  'True Forex Funds',
  'TX3 Funding',
  'UProfit Trader',
  'Wall Street Funded',
].sort();
